version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=kanjibenkyou_db
      - POSTGRES_PASSWORD=s3cr3t!
      - POSTGRES_USER=kanjibenkyou
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./kanji_benkyou_api
    user: "${UID}:${GID}"
    volumes:
      - ./kanji_benkyou_api:/opt/kanji-api:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python", "manage.py", "runserver",  "0.0.0.0:8000"]

volumes:
  pgdata:
