version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=kanjibenkyou_db
      - POSTGRES_PASSWORD=s3cr3t!
      - POSTGRES_USER=kanjibenkyou
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./kanji_benkyou_api
    user: "${UID}:${GID}"
    env_file:
      - ./kanji_benkyou_api/.env
    volumes:
      - ./kanji_benkyou_api:/opt/kanji-api:rw
      - pdfdata:/opt/static:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python", "manage.py", "runserver",  "0.0.0.0:8000"]

  app:
    build: ./kanji-benkyou
    env_file:
      - ./kanji-benkyou/.env
    volumes:
      - ./kanji-benkyou:/opt/kanji-app:rw
    ports:
      - "8080:8080"
    command: ["yarn", "serve"]

volumes:
  pgdata:
  pdfdata:
