version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=kanjibenkyou_db
      - POSTGRES_PASSWORD=s3cr3t!
      - POSTGRES_USER=kanjibenkyou
    volumes:
      - pgdata:/var/lib/postgresql/data

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticdata02:/usr/share/elasticsearch/data

  api:
    build: ./kanji_benkyou_api
    user: "${UID}:${GID}"
    volumes:
      - ./kanji_benkyou_api:/opt/kanji-api:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python", "manage.py", "runserver",  "0.0.0.0:8000"]

volumes:
  pgdata:
  elasticdata01:
  elasticdata02:
